[tool.ruff]
line-length = 95
indent-width = 4
extend-exclude = ['alembic', 'tests']
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-p no:warnings"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff.lint]
exclude = ["alembic", "importacao.py", "tests"]
preview = true
select = ["E", "F", "W", "I", "PL", "PT", "R"]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
exclude = ["alembic", "importacao.py", "tests"]
preview = true
quote-style = "double"
indent-style = "space"

[tool.taskipy.tasks]
run = 'fastapi dev main.py'
pre_test = 'task lint'
test = 'pytest --cov -vv'
post_test = 'coverage html'
lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff  format .'

[tool.mypy]
exclude = ["alembic", "importacao.py", "test"]
ignore_missing_imports = true
strict = true
warn_return_any = true
warn_unused_ignores = false
disallow_untyped_defs = false
disallow_any_unimported = false

