name: Auto Merge Develop to Main

on:
  schedule:
    - cron: '0 0 */3 * *'  
  workflow_dispatch: 

jobs:
  verify:
    name: Verify Develop
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Linter
        run: |
          ruff check .
          mypy .
          
      - name: Run Unit Tests
        run: task test
        
      - name: Verify Build
        run: |
          python -m compileall .
          python -c "import app"

  merge:
    name: Merge Develop to Main
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Merge develop into main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout main
          git pull origin main
          git merge --no-ff develop -m "Auto-merge: Develop into Main via GitHub Actions"
          git push origin main
