name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ou a branch que você quiser

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir /home/ubuntu/app
          cd /home/ubuntu/app
          git pull origin main
          docker-compose up -d --build
