name: Verify Lint

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install lint tools
        run: pip install -r requirements.txt
          
      - name: Run Ruff
        run: ruff check .
        
      - name: Run Mypy
        run: mypy .