name: Check Commit Message  

on:
  workflow_call:

jobs:
  verify-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4  

      - name: Commit message verification
        run: |
          echo "Verificando mensagens de commit..."
          commits=$(git log --format=%s -n 10 --no-merges)
          regex="^(feat|fix|docs|style|refactor|test|chore|build): .+|^Merge .+"
      
          echo "$commits" | while IFS= read -r commit; do
            echo "🔍 Commit encontrado: '$commit'"
            if ! [[ "$commit" =~ $regex ]]; then
              echo "❌ Commit inválido!: '$commit'"
              echo "Os commits devem seguir o padrão: 'type: description'"
              exit 1
            fi
          done
